In [1]:
import numpy as np

In [2]:
#Creating One Dimensional Array
ar=np.array([12,34,56])
print(ar)

[12 34 56]


In [3]:
#Creating Three Dimensional from a Two Dimensional Array using parameter ndmin=3
ar=np.array([[12,34,56],
             [34,33,67]],ndmin=3)
print(ar)
print(type(ar))

[[[12 34 56]
  [34 33 67]]]
<class 'numpy.ndarray'>


In [4]:
# Three Dimensional Array with two Two-Dimensional array
ar=np.array([[[12,34,56],
             [34,33,67]],
             [[12,34,56],
             [34,33,67]]],ndmin=3)
print(ar)
print(type(ar))

[[[12 34 56]
  [34 33 67]]

 [[12 34 56]
  [34 33 67]]]
<class 'numpy.ndarray'>


In [5]:
# Three Dimensional Array with Float values
ar=np.array([[[12,34,56],
             [34,33,67]],
             [[12,34,56],
             [34,33,67]]],dtype=float)
print(ar)
print(type(ar))

[[[12. 34. 56.]
  [34. 33. 67.]]

 [[12. 34. 56.]
  [34. 33. 67.]]]
<class 'numpy.ndarray'>


In [6]:
# Array Operations - Addition
ar=np.array([1,23,45,6])
Ar=ar+5
            
print(Ar)


[ 6 28 50 11]


In [7]:
# One Dimensional Array ar1, Two Dimensional Array ar2, Three Dimensional Array ar3
ar1=np.array([1,23,45,6])
ar2=np.array([[1,2,4],[2,5,6]])
ar3=np.array([[[1,2,4],
               [2,5,6]],
              [[3,6,9],
               [9,0,1]]])
            

In [8]:
#Accessing elements of One Dimensional Array 
ar1[2]

45

In [9]:
#Accessing elements of Two Dimensional Array 
ar2[1,2]

6

In [10]:
#Accessing elements of Three Dimensional Array 
ar3[1,1,0]

9